"""make vault_id nullable

Revision ID: 5b8662da538c
Revises: 7f0a0a0aee90
Create Date: 2026-05-01 00:54:59.077933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8662da538c'
down_revision: Union[str, None] = '7f0a0a0aee90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'vault_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'vault_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
