"""add purpose to vault

Revision ID: c868da0c397a
Revises: ce6b755f8d08
Create Date: 2026-05-01 02:09:42.954615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c868da0c397a'
down_revision: Union[str, None] = 'ce6b755f8d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
