"""add purpose to vault

Revision ID: ce6b755f8d08
Revises: 5b8662da538c
Create Date: 2026-05-01 02:08:02.754263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6b755f8d08'
down_revision: Union[str, None] = '5b8662da538c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaults', sa.Column('purpose', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaults', 'purpose')
    # ### end Alembic commands ###
